In [1]:
import numpy as np

#### Exercise One

In [2]:
array = np.random.rand(500, 20)

In [3]:
np.sum(np.sqrt(array))

6637.73701906571

#### Exercise Two

In [4]:
array = np.loadtxt("RandomeValues.csv", delimiter = ",",skiprows = 0)

In [8]:
array[[5,7,9],:]

array([[ 79.,  67.,  44., 100.,  89.,  71.,  27.,  46.,  45.,  13.,  32.],
       [ 37.,  43.,  10.,  16.,  77.,  40.,  62.,   4.,  22.,  64.,  15.],
       [ 80.,  93.,  76.,  46.,  46.,  35.,  57.,  70.,  93.,  36.,  86.]])

In [9]:
array[:,[0,7,10]]

array([[ 68.,  63.,  14.],
       [  5.,  77.,  33.],
       [  1.,   3.,  26.],
       [ 83.,  32.,  96.],
       [ 71.,  35.,  76.],
       [ 79.,  46.,  32.],
       [100.,  59.,   2.],
       [ 37.,   4.,  15.],
       [ 97.,   7.,  21.],
       [ 80.,  70.,  86.],
       [ 25.,  65.,  45.]])

In [10]:
array[7:10,1:2]

array([[43.],
       [61.],
       [93.]])

#### Exercise Three

In [11]:
row = np.loadtxt("SalesData.csv", delimiter = ",",skiprows = 1, usecols = 0, dtype="<U4")
header = np.loadtxt("SalesData.csv", delimiter = ",", skiprows =0, usecols = (1,2,3,4,5,6,7,8,9,10,11,12), max_rows = 1, dtype="<U6")
data = np.loadtxt("SalesData.csv", delimiter = ",", skiprows =1, usecols = (1,2,3,4,5,6,7,8,9,10,11,12))


In [13]:
data

array([[390., 345., 379., 353., 365., 326., 363., 459., 539., 474., 340.,
        343.],
       [392., 377., 347., 395., 330., 332., 340., 446., 573., 464., 223.,
        216.],
       [250., 270., 300., 398., 376., 382., 306., 489., 552., 488., 298.,
        269.],
       [460., 480., 450., 310., 392., 383., 314., 402., 640., 495., 215.,
        243.],
       [460., 480., 450., 387., 388., 320., 337., 478., 676., 408., 338.,
        263.],
       [470., 510., 360., 472., 423., 385., 353., 464., 598., 419., 459.,
        659.]])

In [14]:
quarter = (header == 'Jul-18') |  (header == 'Aug-18') | (header == 'Sep-18')

In [15]:
np.sum(data[:,quarter],axis=0)


array([2315., 2274., 2128.])

In [16]:
np.mean(data[:,quarter], axis=0)

array([385.83333333, 379.        , 354.66666667])

In [17]:
stores = (row == 'L3') | (row == 'L1')
q1 = (header == 'Apr-18') | (header == 'May-18') |(header == 'Jun-18')
q3 = (header == 'Oct-18') |(header == 'Nov-18') |(header == 'Dec-18') 

In [18]:
print("Q1 sales for stores ", row[stores], " are " , np.sum(data[stores.T,:][:,q1], axis=1))
print("Q3 sales for stores ", row[stores], " are " , np.sum(data[stores.T,:][:,q3], axis=1))

Q1 sales for stores  ['L3' 'L1']  are  [1114. 1116.]
Q3 sales for stores  ['L3' 'L1']  are  [1361. 1359.]


In [19]:
stores = (row == 'N4') | (row == 'N6')

In [20]:
d = data[stores]
d[d>399]=0

In [21]:
print(d)

[[  0.   0.   0. 310. 392. 383. 314.   0.   0.   0. 215. 243.]
 [  0.   0.   0. 387. 388. 320. 337.   0.   0.   0. 338. 263.]]


#### Exercise 4

In [ ]:
iters = 2000 # number of iterations
steps = 1000 # steps
start = 3 # starting position 

In [ ]:
draws = np.random.randint(0,2,size=(iters,steps))

In [ ]:
steps = np.where(draws > 0,1,-1)

In [ ]:
steps[:,0] += start # account for the starting position 

In [ ]:
walks = np.cumsum(steps,axis=1)

In [ ]:
mask = [(walks > 7) | (walks < 0)]

In [ ]:
all = np.ma.MaskedArray(walks,mask,fill_value=999).count(axis=1)

In [ ]:
print("Average # steps ", np.mean(all))
print("Median # steps ", np.median(all))
print("Steps standard deviation ", np.std(all))
print("Min # steps ", all.min())
print("Max # steps ", all.max())

In [ ]:
import matplotlib.pyplot as plt
fig, axs = plt.subplots(1, 1, 
                        figsize =(10, 7),  
                        tight_layout = True) 
  
axs.hist(all, bins = 100) 
# Adding extra features     
plt.xlabel("Number of Steps") 
plt.ylabel("Frequency") 
plt.title('A Bug Random Walk')   
# Show plot 
plt.show() 